from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd


PASSIVATORS = ("3MTPAI", "PDAI2", "EDAI2", "PipDI")
DEFAULT_DATA_PATH = Path(__file__).resolve().parent / "demo_optimization_table.csv"
SUPPORTED_LANGUAGES = ("en", "zh")

UI_TEXT = {
    "app_title": {
        "en": "PVK-BO Agent Demo",
        "zh": "PVK-BO Agent 演示",
    },
    "app_caption": {
        "en": "A leader-facing workflow demo for perovskite passivation formulation optimization.",
        "zh": "面向 leader 的钙钛矿钝化配方优化工作流演示。",
    },
    "demo_warning": {
        "en": "Demo workflow only. Results are not experimentally validated and do not prove real BO performance.",
        "zh": "仅用于演示工作流。结果未经实验验证，也不证明真实 BO 性能。",
    },
    "language": {"en": "Language", "zh": "语言"},
    "setup_tab": {"en": "1. Setup", "zh": "1. 任务设置"},
    "data_tab": {"en": "2. Data + Analysis", "zh": "2. 数据与分析"},
    "recommendation_tab": {
        "en": "3. Recommendation + Plan",
        "zh": "3. 推荐与实验方案",
    },
    "feedback_tab": {
        "en": "4. Simulated Feedback Loop",
        "zh": "4. 模拟回填闭环",
    },
    "agent_team": {"en": "Agent Team", "zh": "Agent 团队"},
    "data_boundary": {"en": "Data Boundary", "zh": "数据边界"},
    "records": {"en": "Records", "zh": "记录数"},
    "best_pce": {"en": "Best PCE", "zh": "最佳 PCE"},
    "sidebar_boundary_note": {
        "en": "P0 uses a rules/mock-acquisition pipeline, not validated BO.",
        "zh": "P0 使用规则/mock acquisition 流水线，不是已验证 BO。",
    },
    "task_setup": {"en": "Task Setup", "zh": "任务设置"},
    "natural_language_task": {
        "en": "Natural-language task",
        "zh": "自然语言任务",
    },
    "default_task": {
        "en": (
            "Design a passivation formulation optimization experiment for normal-bandgap "
            "perovskite solar cells. Improve PCE while monitoring Voc, FF, and stability."
        ),
        "zh": "设计一个正常带隙钙钛矿太阳能电池钝化配方优化实验，提高 PCE，并监控 Voc、FF 和稳定性。",
    },
    "primary_objective": {"en": "Primary objective", "zh": "主目标"},
    "maximize_pce": {"en": "Maximize PCE", "zh": "最大化 PCE"},
    "candidates": {"en": "Candidates", "zh": "候选钝化剂"},
    "demo_mode": {"en": "Demo mode", "zh": "演示模式"},
    "csv_rules": {"en": "CSV + rules", "zh": "CSV + 规则"},
    "setup_info": {
        "en": (
            "This demo mirrors AutoPolyAgent-style staged orchestration: data grounding, "
            "domain hypothesis, candidate scoring, critic review, experiment planning, and reporting."
        ),
        "zh": "该 demo 参考 AutoPolyAgent 的分阶段编排：数据锚定、领域假设、候选评分、风险审查、实验规划与报告。",
    },
    "data_grounding": {"en": "Data Grounding", "zh": "数据锚定"},
    "total_records": {"en": "Total records", "zh": "总记录数"},
    "mean_pce": {"en": "Mean PCE", "zh": "平均 PCE"},
    "real_pipdi_samples": {"en": "Real PipDI samples", "zh": "真实 PipDI 样本"},
    "data_health": {"en": "Data Health", "zh": "数据健康"},
    "current_best_evidence": {
        "en": "Current Best Evidence",
        "zh": "当前最佳证据",
    },
    "evidence_text": {"en": "Evidence text", "zh": "证据文本"},
    "no_evidence": {
        "en": "No evidence text available.",
        "zh": "暂无证据文本。",
    },
    "passivator_distribution": {
        "en": "Passivator Distribution",
        "zh": "钝化剂分布",
    },
    "demo_table_preview": {
        "en": "Demo Table Preview",
        "zh": "Demo 数据表预览",
    },
    "recommendation_plan": {
        "en": "Recommendation + Experiment Plan",
        "zh": "推荐与实验方案",
    },
    "recommendation_caption": {
        "en": "Generated by a lightweight agent-team pipeline with explicit data boundaries.",
        "zh": "由轻量 agent-team 流水线生成，并显式标注数据边界。",
    },
    "recommendation_count": {
        "en": "Number of next experiments",
        "zh": "下一轮实验数量",
    },
    "generate_next": {"en": "Generate Next Experiments", "zh": "生成下一轮实验"},
    "running_pipeline": {
        "en": "Running Data -> Domain -> Optimizer -> Critic -> Planner pipeline...",
        "zh": "正在运行 Data -> Domain -> Optimizer -> Critic -> Planner 流水线...",
    },
    "no_recommendations": {
        "en": "No recommendations available. Falling back to the bundled demo CSV is required.",
        "zh": "暂无推荐。需要回退到内置 demo CSV。",
    },
    "type": {"en": "Type", "zh": "类型"},
    "risk": {"en": "Risk", "zh": "风险"},
    "mock_score": {"en": "Mock score", "zh": "模拟分数"},
    "validation": {"en": "Validation", "zh": "验证"},
    "required": {"en": "Required", "zh": "需要"},
    "data_boundary_label": {"en": "Data boundary", "zh": "数据边界"},
    "high_risk_warning": {
        "en": "High-risk demo-only candidate. Do not treat as validated science.",
        "zh": "高风险 demo-only 候选。不要视为已验证科学结论。",
    },
    "experiment_plan_evidence": {
        "en": "Experiment plan and evidence",
        "zh": "实验方案与证据",
    },
    "process_assumptions": {
        "en": "Process assumptions",
        "zh": "工艺假设",
    },
    "steps": {"en": "Steps", "zh": "步骤"},
    "reason": {"en": "Reason", "zh": "理由"},
    "risks": {"en": "Risks", "zh": "风险"},
    "hypothesis_to_validate": {
        "en": "Hypothesis to validate",
        "zh": "待验证假设",
    },
    "supporting_records": {
        "en": "Supporting records",
        "zh": "支持记录",
    },
    "demo_only_hypothesis": {
        "en": "Demo-only hypothesis",
        "zh": "仅用于 demo 的假设",
    },
    "feedback_loop": {
        "en": "Simulated Feedback Loop",
        "zh": "模拟回填闭环",
    },
    "feedback_caption": {
        "en": "This section validates the workflow shape, not algorithm performance.",
        "zh": "本部分验证工作流形态，不验证算法性能。",
    },
    "simulate_feedback": {
        "en": "Simulate Experiment Feedback",
        "zh": "模拟实验回填",
    },
    "round_labels": {"en": "Round labels", "zh": "轮次标签"},
}


@dataclass(frozen=True)
class PipelineStage:
    name: str
    responsibility: str
    output_summary: str


@dataclass(frozen=True)
class DataSummary:
    total_records: int
    best_pce: float
    mean_pce: float
    best_experiment: dict[str, Any]
    passivator_counts: dict[str, int]
    data_type_counts: dict[str, int]
    pipdi_real_sample_count: int
    data_health_notes: list[str]


@dataclass(frozen=True)
class Recommendation:
    experiment_id: str
    recommendation_type: str
    passivator_combination: str
    process: dict[str, Any]
    mock_acquisition_score: float
    supporting_records: list[str]
    evidence_level: str
    data_boundary: str
    reason: str
    risk_level: str
    risks: list[str]
    hypothesis: str
    validation_required: bool
    steps: list[str]
    observations: list[str]


def ui_text(key: str, language: str = "en") -> str:
    language = language if language in SUPPORTED_LANGUAGES else "en"
    entry = UI_TEXT.get(key)
    if entry is None:
        return key
    return entry.get(language, entry["en"])


def load_experiment_data(path: str | Path = DEFAULT_DATA_PATH) -> pd.DataFrame:
    """Load the demo CSV and normalize the current extracted schema."""
    data = pd.read_csv(path)
    normalized = data.copy()

    if "PCE" not in normalized.columns and "PCE_percent" in normalized.columns:
        normalized["PCE"] = pd.to_numeric(normalized["PCE_percent"], errors="coerce")

    if "passivator_system" not in normalized.columns:
        if "passivator_combo" in normalized.columns:
            normalized["passivator_system"] = normalized["passivator_combo"].fillna(
                "Not specified"
            )
        else:
            normalized["passivator_system"] = "Not specified"

    for passivator in PASSIVATORS:
        column = f"has_{passivator}"
        if column not in normalized.columns:
            normalized[column] = 0
        normalized[column] = pd.to_numeric(normalized[column], errors="coerce").fillna(0)

    if "data_type" not in normalized.columns:
        normalized["data_type"] = "unknown"

    if "evidence_text" not in normalized.columns:
        normalized["evidence_text"] = ""

    return normalized


def build_data_summary(data: pd.DataFrame) -> DataSummary:
    data = _normalize_dataframe(data)
    total_records = int(len(data))
    if total_records == 0:
        return DataSummary(
            total_records=0,
            best_pce=0.0,
            mean_pce=0.0,
            best_experiment={},
            passivator_counts={passivator: 0 for passivator in PASSIVATORS},
            data_type_counts={},
            pipdi_real_sample_count=0,
            data_health_notes=["No records loaded. Use the bundled demo CSV to run the demo."],
        )

    pce = pd.to_numeric(data.get("PCE", pd.Series(dtype=float)), errors="coerce")
    best_index = pce.idxmax() if pce.notna().any() else data.index[0]
    best_row = data.loc[best_index].to_dict()
    best_pce = _safe_float(best_row.get("PCE"))

    passivator_counts = {
        passivator: int(pd.to_numeric(data[f"has_{passivator}"], errors="coerce").fillna(0).sum())
        for passivator in PASSIVATORS
    }
    data_type_counts = {
        str(data_type): int(count)
        for data_type, count in data["data_type"].fillna("unknown").value_counts().items()
    }
    pipdi_real_sample_count = int(
        data[
            (pd.to_numeric(data["has_PipDI"], errors="coerce").fillna(0) > 0)
            & (data["data_type"] != "simulated_for_demo")
        ].shape[0]
    )

    notes = [
        f"Loaded {total_records} demo records from the structured CSV.",
        "PCE values are literature-extracted or manually curated demo evidence, not a controlled BO benchmark.",
    ]
    if pipdi_real_sample_count == 0:
        notes.append("PipDI has no real sample in the current dataset; treat it as demo-only exploration.")
    if "concentration_text" in data.columns:
        missing_or_text = data["concentration_text"].fillna("").astype(str).str.strip()
        if (missing_or_text == "").any() or missing_or_text.str.contains(r"[a-zA-Z]", regex=True).any():
            notes.append("Concentration values are mixed text units; P0 uses rules instead of real BO.")
    if "perovskite_system" in data.columns and len(data["perovskite_system"].dropna().unique()) > 1:
        notes.append("Records span multiple perovskite systems; avoid causal cross-system PCE claims.")

    return DataSummary(
        total_records=total_records,
        best_pce=round(best_pce, 2),
        mean_pce=round(float(pce.mean()) if pce.notna().any() else 0.0, 2),
        best_experiment=best_row,
        passivator_counts=passivator_counts,
        data_type_counts=data_type_counts,
        pipdi_real_sample_count=pipdi_real_sample_count,
        data_health_notes=notes,
    )


def build_agent_pipeline() -> list[PipelineStage]:
    return [
        PipelineStage(
            name="Data Agent",
            responsibility="Load the CSV, normalize fields, and expose data health.",
            output_summary="DataFrame, best experiment, passivator counts, and evidence snippets.",
        ),
        PipelineStage(
            name="Domain Agent",
            responsibility="Translate passivator evidence into cautious domain hypotheses.",
            output_summary="Mechanism hypotheses labeled as unvalidated and evidence-bound.",
        ),
        PipelineStage(
            name="Optimizer Agent",
            responsibility="Create rule-based next-batch candidates for demo-only scoring.",
            output_summary="Exploitation, exploration, balanced, and control recommendations.",
        ),
        PipelineStage(
            name="Critic Agent",
            responsibility="Check recommendations for data-boundary and scientific-claim risks.",
            output_summary="Risk level, data-boundary label, and validation requirements.",
        ),
        PipelineStage(
            name="Experiment Planner Agent",
            responsibility="Turn reviewed candidates into executable experimental plans.",
            output_summary="Formula, fixed process assumptions, steps, observations, and controls.",
        ),
        PipelineStage(
            name="Reporter Agent",
            responsibility="Package the leader demo as a clear workflow narrative.",
            output_summary="Synthetic feedback loop and demo-only reporting copy.",
        ),
    ]


def generate_recommendations(
    data: pd.DataFrame, summary: DataSummary, n: int = 5
) -> list[Recommendation]:
    n = max(1, min(n, 5))
    best_id = str(summary.best_experiment.get("experiment_id", "current-best"))
    best_combo = str(summary.best_experiment.get("passivator_system", "EDAI2"))

    candidates = [
        Recommendation(
            experiment_id="NEXT-01",
            recommendation_type="Exploitation",
            passivator_combination=best_combo,
            process=_fixed_process(summary.best_experiment),
            mock_acquisition_score=0.91,
            supporting_records=[best_id],
            evidence_level="literature-grounded seed",
            data_boundary="demo grounding, not validated optimization",
            reason="Stay close to the current high-PCE seed while adjusting only one controllable condition.",
            risk_level="Low",
            risks=["Cross-paper conditions may differ from the demo task system."],
            hypothesis="A nearby formulation may preserve the observed high-PCE behavior under controlled follow-up.",
            validation_required=True,
            steps=_standard_steps(),
            observations=["PCE", "Voc", "FF", "repeatability against the current seed"],
        ),
        Recommendation(
            experiment_id="NEXT-02",
            recommendation_type="Exploration",
            passivator_combination="EDAI2 + low-dose PipDI",
            process={"solvent": "IPA", "spin_speed_rpm": 4000, "spin_time_s": 30, "anneal_temp_C": 100, "anneal_time_min": 5},
            mock_acquisition_score=0.83,
            supporting_records=[best_id],
            evidence_level="demo-only hypothesis",
            data_boundary="demo-only exploration",
            reason="PipDI is absent from the current evidence table, so it is useful only as a visible exploration candidate.",
            risk_level="High",
            risks=["No real PipDI sample exists in the current dataset.", "Solubility and interface compatibility are unknown."],
            hypothesis="A low-dose exploratory passivator may reveal whether the unobserved candidate deserves real data collection.",
            validation_required=True,
            steps=_standard_steps(),
            observations=["film morphology", "Voc drift", "PCE repeatability", "solubility issues"],
        ),
        Recommendation(
            experiment_id="NEXT-03",
            recommendation_type="Control",
            passivator_combination="EDAI2 only control",
            process={"solvent": "IPA", "spin_speed_rpm": 3000, "spin_time_s": 30, "anneal_temp_C": 100, "anneal_time_min": 2},
            mock_acquisition_score=0.72,
            supporting_records=_top_records(data, passivator="EDAI2", limit=2),
            evidence_level="literature-extracted control anchor",
            data_boundary="demo grounding, not causal proof",
            reason="Hold the strongest observed passivator family as a control before adding new variables.",
            risk_level="Medium",
            risks=["EDAI2 records come from mixed systems and cannot prove causality."],
            hypothesis="An EDAI2-only control gives the demo batch an interpretable baseline.",
            validation_required=True,
            steps=_standard_steps(),
            observations=["PCE", "Voc", "FF", "control-vs-combination delta"],
        ),
        Recommendation(
            experiment_id="NEXT-04",
            recommendation_type="Balanced",
            passivator_combination="3MTPAI + PDAI2",
            process={"solvent": "IPA/CB 1:1", "spin_speed_rpm": 5000, "spin_time_s": 30, "anneal_temp_C": 100, "anneal_time_min": 10},
            mock_acquisition_score=0.86,
            supporting_records=_top_records(data, passivator="3MTPAI", limit=2),
            evidence_level="limited high-PCE seed",
            data_boundary="demo grounding, not validated optimization",
            reason="Use the observed 3MTPAI + PDAI2 high-performance seed as a visible exploitation-plus-interpretability candidate.",
            risk_level="Medium",
            risks=["The current concentration text is not normalized to mM.", "Mixed solvent conditions are copied as demo assumptions."],
            hypothesis="The diammonium/alkylammonium combination may support interface passivation while preserving transport.",
            validation_required=True,
            steps=_standard_steps(),
            observations=["PCE", "Voc", "FF", "surface uniformity"],
        ),
        Recommendation(
            experiment_id="NEXT-05",
            recommendation_type="Ablation",
            passivator_combination="PDAI2 only ablation",
            process={"solvent": "IPA/CB 1:1", "spin_speed_rpm": 4500, "spin_time_s": 25, "anneal_temp_C": 100, "anneal_time_min": 10},
            mock_acquisition_score=0.69,
            supporting_records=_top_records(data, passivator="PDAI2", limit=2),
            evidence_level="literature-extracted ablation anchor",
            data_boundary="demo grounding, not causal proof",
            reason="Remove 3MTPAI from the combination to make the next batch more diagnostically useful.",
            risk_level="Medium",
            risks=["Single-factor attribution remains weak without matched controls."],
            hypothesis="If PDAI2-only remains competitive, it may simplify the next experimental batch.",
            validation_required=True,
            steps=_standard_steps(),
            observations=["PCE", "Voc", "FF", "comparison against 3MTPAI + PDAI2"],
        ),
    ]
    return candidates[:n]


def simulate_feedback(
    summary: DataSummary, recommendations: list[Recommendation]
) -> dict[str, Any]:
    best = summary.best_pce
    if recommendations:
        simulated_best = round(best + min(0.4, 0.1 + recommendations[0].mock_acquisition_score / 10), 2)
    else:
        simulated_best = best
    return {
        "rounds": ["Initial data", "Recommended batch", "Simulated feedback"],
        "best_so_far": [best, best, simulated_best],
        "uncertainty_label": ["mixed literature data", "next batch proposed", "synthetic result"],
        "caption": "Synthetic walkthrough only. Not experimental validation and not an algorithm benchmark.",
    }


def _fixed_process(row: dict[str, Any]) -> dict[str, Any]:
    return {
        "solvent": row.get("solvent") or "IPA",
        "spin_speed_rpm": _safe_int(row.get("spin_speed_rpm"), default=4000),
        "spin_time_s": _safe_int(row.get("spin_time_s"), default=30),
        "anneal_temp_C": _safe_int(row.get("anneal_temp_C"), default=100),
        "anneal_time_min": _safe_int(row.get("anneal_time_min"), default=5),
    }


def _standard_steps() -> list[str]:
    return [
        "Prepare the passivation solution using the stated demo formulation.",
        "Spin-coat the passivation solution on the perovskite film under the fixed demo process.",
        "Anneal under the stated demo condition.",
        "Complete downstream transport layers and electrodes according to the baseline process.",
        "Measure PCE, Voc, Jsc, FF, and capture qualitative film observations.",
    ]


def _top_records(data: pd.DataFrame, passivator: str, limit: int = 2) -> list[str]:
    column = f"has_{passivator}"
    if column not in data.columns or "PCE" not in data.columns:
        return []
    subset = data[pd.to_numeric(data[column], errors="coerce").fillna(0) > 0]
    subset = subset.sort_values("PCE", ascending=False)
    return [str(record_id) for record_id in subset["experiment_id"].head(limit).tolist()]


def _normalize_dataframe(data: pd.DataFrame) -> pd.DataFrame:
    normalized = data.copy()
    if "PCE" not in normalized.columns and "PCE_percent" in normalized.columns:
        normalized["PCE"] = pd.to_numeric(normalized["PCE_percent"], errors="coerce")
    if "passivator_system" not in normalized.columns:
        normalized["passivator_system"] = normalized.get("passivator_combo", "Not specified")
    if "data_type" not in normalized.columns:
        normalized["data_type"] = "unknown"
    for passivator in PASSIVATORS:
        column = f"has_{passivator}"
        if column not in normalized.columns:
            normalized[column] = 0
        normalized[column] = pd.to_numeric(normalized[column], errors="coerce").fillna(0)
    return normalized


def _safe_float(value: Any, default: float = 0.0) -> float:
    try:
        if pd.isna(value):
            return default
        return float(value)
    except (TypeError, ValueError):
        return default


def _safe_int(value: Any, default: int) -> int:
    try:
        if pd.isna(value):
            return default
        return int(float(value))
    except (TypeError, ValueError):
        return default
